//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez sélectionné une date. Vous receverez des informations par rapport à cette date dans le futur!.
        /// </summary>
        internal static string Date_Choisie {
            get {
                return ResourceManager.GetString("Date_Choisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici une belle image pour vous accueillir  sur notre site dédier au amateur de la Pologne!.
        /// </summary>
        internal static string Info_Accueil {
            get {
                return ResourceManager.GetString("Info_Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez consulter ici le nom de différentes villes de Pologne. Cliquez sur le lien suivant pour plus d&apos;informations..
        /// </summary>
        internal static string Info_BD {
            get {
                return ResourceManager.GetString("Info_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acceuil.
        /// </summary>
        internal static string Info_BT_Accueil {
            get {
                return ResourceManager.GetString("Info_BT_Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Festivals.
        /// </summary>
        internal static string Info_BT_Festivals {
            get {
                return ResourceManager.GetString("Info_BT_Festivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Krakow.
        /// </summary>
        internal static string Info_BT_Krakow {
            get {
                return ResourceManager.GetString("Info_BT_Krakow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string Info_BT_Login {
            get {
                return ResourceManager.GetString("Info_BT_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        internal static string Info_BT_Photo {
            get {
                return ResourceManager.GetString("Info_BT_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poznan.
        /// </summary>
        internal static string Info_BT_Poznan {
            get {
                return ResourceManager.GetString("Info_BT_Poznan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Varsovie.
        /// </summary>
        internal static string Info_BT_Varsovie {
            get {
                return ResourceManager.GetString("Info_BT_Varsovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une ville.
        /// </summary>
        internal static string Info_BT_Ville {
            get {
                return ResourceManager.GetString("Info_BT_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Villes.
        /// </summary>
        internal static string Info_BT_Ville2 {
            get {
                return ResourceManager.GetString("Info_BT_Ville2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez ici enregistrer une date pour recevoir des informations sur les festivals disponibles en Pologne près de cette date!.
        /// </summary>
        internal static string Info_Calendrier {
            get {
                return ResourceManager.GetString("Info_Calendrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer l&apos;identifiant de la ville :.
        /// </summary>
        internal static string Info_ID_Ville {
            get {
                return ResourceManager.GetString("Info_ID_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici une belle image de la ville de Krakow!.
        /// </summary>
        internal static string Info_Krakow {
            get {
                return ResourceManager.GetString("Info_Krakow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom de la ville :.
        /// </summary>
        internal static string Info_Nom_ville {
            get {
                return ResourceManager.GetString("Info_Nom_ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer votre mot de passe :.
        /// </summary>
        internal static string Info_Password {
            get {
                return ResourceManager.GetString("Info_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici une belle image de la ville de Poznan!.
        /// </summary>
        internal static string Info_Poznan {
            get {
                return ResourceManager.GetString("Info_Poznan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer votre nom d&apos;utilisateur :.
        /// </summary>
        internal static string Info_Username {
            get {
                return ResourceManager.GetString("Info_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici une belle image de la ville de Varsovie!.
        /// </summary>
        internal static string Info_Warsaw {
            get {
                return ResourceManager.GetString("Info_Warsaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Obligatoire).
        /// </summary>
        internal static string Mess_Erreur {
            get {
                return ResourceManager.GetString("Mess_Erreur", resourceCulture);
            }
        }
    }
}
