<%@ Page Title="" Language="C#" MasterPageFile="~/PageMaître.Master" AutoEventWireup="true" CodeBehind="PageAffichageVille.aspx.cs" Inherits="WebApplication24.WebForm1" UICulture="auto"%>

<%--Programmeur : Alex Boudreault
Dernière modification le : 17 décembre 2017
Objectif de la page : Cette page à pour but d'afficher un gridview
qui contient des villes de la Pologne. Il sera possible d'ajouter de modifier
ou de supprimer une ville et les villes seront affichées trois par pages.--%>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    
    <%--On créer tous les éléments de mise en page pour le GridView
        et le texte--%>
    <style>
        .GridViewBordure{
            padding:5%;
            border:3px solid black;
            margin-left: 30%;
            margin-top: 10%;
            margin-right: 36%;
            margin-bottom: 20%;
            border-color: #3399ff;
        }
        .LB
        {
            
            color: #3399ff;
            font-weight: bold;
            font-size: 30px;
        }
        .GridView
        {
            background-color: #b3e6ff;
            font: 16px Arial, Sans-Serif;
            
    
        }
        .GridView td, .GridView th
        {
            padding: 10px;
        }
        .GridViewHeader
        {
            text-align: left;
            color: black;
            background-color: #ffffcc;
        }
        .GridViewRow td
        {
            border-bottom: solid 1px black;
        }
        .GridViewAlternating
        {
            background-color: #ffffcc;
        }
        .GridViewAlternating td
        {
            border-bottom: solid 1px black;
        }
        .Label
        {
            color: #3399ff;
            font-weight: bold;
        }
        .PageStyle
        {
            background-color: #ffffcc;
        }
        .Link
        {
            color: #3399ff;
            font-size: 30px;
        }
    </style>

    <%--On créer une source de données qui contient les données du GridView --%>
    <asp:SqlDataSource 
        ID="SqlDataSource1" 
        runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        SelectCommand="SELECT * FROM [Ville]"
        UpdateCommand="UPDATE Ville SET Ville=@Ville WHERE ID_Ville = @ID_Ville"
        DeleteCommand="DELETE VILLE WHERE ID_Ville = @ID_Ville">
    </asp:SqlDataSource>

    <%--On créer une division pour l'intérieur du cadre --%>
    <div class="GridViewBordure">
    
    <%--On créer un Label pour contenir l'information --%>
    <asp:Label runat="server" CssClass="LB" 
        Text="<%$ Resources:Site, Info_BD %>">
    </asp:Label>
    
    <asp:HyperLink
         ID="Lien_Liste_Ville"
         runat="server"
         Text="-->"
         NavigateUrl="https://en.wikipedia.org/wiki/List_of_cities_and_towns_in_Poland"
         CssClass="">
    </asp:HyperLink>

    <%--On créer le GridView et on ajuste ces paramètres --%>
    <asp:GridView
        ID="GV_Ville"
        runat="server" 
        AutoGenerateColumns="False" 
        DataKeyNames="ID_Ville" 
        DataSourceID="SqlDataSource1"
        CssClass="GridView"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        AlternatingRowStyle-CssClass="GridViewAlternating"
        RowStyle-CssClass="GridViewRow"
        HeaderStyle-CssClass="GridViewHeader"
        AllowPaging="true" 
        PageSize="3" 
        Width="387px" 
        Height="332px"  
        PagerStyle-CssClass="PageStyle">
        <Columns>
            <asp:BoundField DataField="ID_Ville" HeaderText="ID_Ville" ReadOnly="True" SortExpression="ID_Ville" />
            <asp:BoundField DataField="Ville" HeaderText="Ville" SortExpression="Ville" />
        </Columns>
    </asp:GridView>
    
    <%--On créer un Label pour le TextBox d'identifiant de ville --%>
    <asp:Label ID="LB_ID_Ville" runat="server" CssClass="Label" Text="<%$ Resources:Site, Info_ID_Ville %>"/>
    
    <%--On créer un TextBox pour l'identifiant de ville --%>    
    <asp:TextBox ID="TB_ID_Vile" runat="server" />

    <%--Changement de ligne --%>
    <br />
    
    <%--On créer un Label pour le TextBox d'identifiant de ville --%>
    <asp:Label ID="LB_Nom_Ville" runat="server" CssClass="Label" Text="<%$ Resources:Site, Info_Nom_Ville %>" />
    
    <%--On créer un TextBox pour l'identifiant de ville --%>     
    <asp:TextBox ID="TB_Nom_Ville" runat="server" />
    
    <%--Changement de ligne --%>    
    <br />

    <%--On créer un bouton pour ajouter la ville saisie par l'utilisateur --%>
    <asp:Button ID="BT_ajout" runat="server" Text="<%$ Resources:Site, Info_BT_Ville %>" OnClick="BT_ajout_Click" />
    </div>
</asp:Content>

